--- #YAML:1.0
name:               App-Prove-Plugin-Cluster
version:            0.01
abstract:           Supports distribution of tests across a cluster, such as LSF
author:
    - Various employees of the Washington University Genome Institute
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  6.31
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
