---
abstract: 'Supports distribution of tests across a cluster, such as LSF'
author:
  - 'Various employees of the Washington University Genome Institute'
build_requires:
  Test::Most: 0.21
  Try::Tiny: 0.09
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101900, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Prove-Plugin-Cluster
requires:
  Test::Harness: 3.23
version: 0.02
